Here's the failing test:
    #test the command_p function empty stack
    def test_command_p_domain_incorrect(self):
        #create a calculator
        calc = minidc()
        #redirect stderr to something we can read
        stderr_temp = sys.stdout
        out = StringIO.StringIO()
        sys.stderr = out

        try:
            #run the divide command (with only 1 value)
            calc.command_p()
            #get the value printed
            printed = out.getvalue()
        finally:
            #restore stdout
            sys.stderr = stderr_temp
        self.assertEqual(printed, 'Error: empty stack\n')
Here's the test failing:
    test_add_domain_correct (__main__.test_minidc) ... ok
    test_add_domain_incorrect (__main__.test_minidc) ... ok
    test_command_f_domain_correct (__main__.test_minidc) ... ok
    test_command_n_domain_correct (__main__.test_minidc) ... ok
    test_command_p_domain_correct (__main__.test_minidc) ... ok
    test_command_p_domain_incorrect (__main__.test_minidc) ... ERROR
    test_divide_domain_correct (__main__.test_minidc) ... ok
    test_divide_domain_incorrect_1 (__main__.test_minidc) ... ok
    test_divide_domain_incorrect_2 (__main__.test_minidc) ... ok
    test_execute_line_domain_correct_1 (__main__.test_minidc) ... ok
    test_execute_line_domain_correct_2 (__main__.test_minidc) ... ok
    test_multiply_domain_correct (__main__.test_minidc) ... ok
    test_multiply_domain_incorrect (__main__.test_minidc) ... ok
    test_push_number_domain_correct (__main__.test_minidc) ... ok
    test_subtract_domain_correct (__main__.test_minidc) ... ok
    test_subtract_domain_incorrect (__main__.test_minidc) ... ok
    ======================================================================
    ERROR: test_command_p_domain_incorrect (__main__.test_minidc)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "V:/softengprac/test_minidc.py", line 307, in test_command_p_domain_incorrect
        calc.command_p()
      File "V:\softengprac\minidc.py", line 77, in command_p
        topnum = self.nums.pop()
    IndexError: pop from empty list
    ----------------------------------------------------------------------
    Ran 16 tests in 0.006s
    FAILED (errors=1)
    Process finished with exit code 0
Here's the code that passes the test:
    #peeks at the top number on the stack and prints it out
    def command_p(self):
        if len(self.nums) == 0:
            sys.stderr.write('Error: empty stack\n')
            return
        #pop the top number off the stack
        topnum = self.nums.pop()
        #push it back onto the stack
        self.nums.append(topnum)
        #print the number to stdout, stripping trailing zeroes
        print '{0:g}'.format(float(topnum))
Here's the test passing:
    test_add_domain_correct (__main__.test_minidc) ... ok
    test_add_domain_incorrect (__main__.test_minidc) ... ok
    test_command_f_domain_correct (__main__.test_minidc) ... ok
    test_command_n_domain_correct (__main__.test_minidc) ... ok
    test_command_p_domain_correct (__main__.test_minidc) ... ok
    test_command_p_domain_incorrect (__main__.test_minidc) ... ok
    test_divide_domain_correct (__main__.test_minidc) ... ok
    test_divide_domain_incorrect_1 (__main__.test_minidc) ... ok
    test_divide_domain_incorrect_2 (__main__.test_minidc) ... ok
    test_execute_line_domain_correct_1 (__main__.test_minidc) ... ok
    test_execute_line_domain_correct_2 (__main__.test_minidc) ... ok
    test_multiply_domain_correct (__main__.test_minidc) ... ok
    test_multiply_domain_incorrect (__main__.test_minidc) ... ok
    test_push_number_domain_correct (__main__.test_minidc) ... ok
    test_subtract_domain_correct (__main__.test_minidc) ... ok
    test_subtract_domain_incorrect (__main__.test_minidc) ... ok
    ----------------------------------------------------------------------
    Ran 16 tests in 0.001s
    OK
    Process finished with exit code 0